name: build-container

on:
  pull_request:
  push:
    branches: [ master ]

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

  # Daily build
  schedule:
    - cron: "0 2 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: |
          echo "is_master: -> ${{ github.ref == 'refs/heads/master' }} <-"
          echo "ref: ${{ github.head_ref }}"

      - name: Set up QEMU (required for arm build)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push master
        uses: docker/build-push-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          pull: true
          tags: latest

      - name: Build PR
        uses: docker/build-push-action@v3
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false
          pull: true
          tags: ${{ github.head_ref}}
